name: hireny
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  injectable: ^2.5.0
  intl:
  table_calendar:
  google_fonts:
  get_it:
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  csc_picker: ^0.2.7
  dropdown_button2: ^2.3.9
  flutter_bloc: ^9.1.0
  dio:
  hive:
  hive_flutter:

  lottie: ^3.3.1
  pretty_dio_logger: ^1.4.0
  animate_do: ^4.2.0
  path_provider: ^2.1.5
  icons_launcher: ^3.0.1
  file_picker:
  permission_handler:
  dropdown_search: ^6.0.2
  flutter_native_splash: ^2.4.6
  fluttertoast: ^8.2.12
  flutter_otp_text_field: ^1.5.1+1
  flutter_local_notifications: ^19.3.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  hive_generator:
  build_runner:
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/country_city/
    - assets/jsons/
  # To add assets to your application, add an assets section, like this:
icons_launcher:
  image_path: "assets/images/hireny.png"
  platforms:
    android:
      adaptive_foreground_image: "assets/images/hireny.png"
      enable: true
      adaptive_background_color: "#FFFFFF"

flutter_native_splash:
  ios: false
  background_image: "assets/images/splash3.png"
  android_12:
    color: "#FFFFFF"
    image: assets/images/icon_splash.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
